baseURL = 'https://matthewkavanagh.us/'
languageCode = 'en-us'
title = 'matthewkavanagh.us'
theme = 'PaperMod'
publishDir = "/var/www/blog/public"

[params]
  mainSections = ["posts"]
  homeInfoParams = { Title = "Matthew Kavanagh", Content = "Adventures in technological exploration. Intermittent ramblings and guides from a tech nerd learning how to automate his life. Join me as I explore Linux, systems programming, microelectronics, and the latest tech news." }
  favicon = "favicon.ico"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/mkavanagh-23"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/mk-radio"

[[params.socialIcons]]
  name = "email"
  url = "mailto:matt@matthewkavanagh.us"

[[params.socialIcons]]
  name = "rss"
  url = "index.xml"

[markup]
  [markup.highlight]
    noClasses = true
    style = "nord"
    lineNos = false
